# Defaults tasks for role ipa-client

- name: Installing required IPA client pkg
  yum:
    name: ['ipa-client', 'krb5-pkinit']
    state: installed

- name: Enrolling node in IPA - DNS SRV lookup mode
  command:
    cmd: "ipa-client-install
         --hostname={{ inventory_hostname }}
         --domain={{ ipa_client_domain }}
         --realm={{ ipa_client_realm}}
         --principal={{ ipa_client_enroll_user }}
         --password={{ ipa_client_enroll_pass }}
         --mkhomedir
         --no-ntp
         --unattended
         --log-file=/var/log/ipa-ansible-enroll.log
         "
    creates: /etc/ipa/default.conf
  no_log: True
  when: ipa_client_use_dns  
  register: enrolled

- name: Enrolling node in IPA - manual/declared server mode
  command:
    cmd: "ipa-client-install
         --hostname={{ inventory_hostname }}
         --domain={{ ipa_client_domain }}
         --realm={{ ipa_client_realm}}
         --principal={{ ipa_client_enroll_user }}
         --password={{ ipa_client_enroll_pass }}
         --mkhomedir
         --no-ntp
         --unattended
         --log-file=/var/log/ipa-ansible-enroll.log
         --fixed-primary
         --server={{ ipa_client_server }}
         "
    creates: /etc/ipa/default.conf
  no_log: True
  when: not ipa_client_use_dns  
  register: enrolled

- block:
    - name: Cleaning up ipa install log
      file:
        path: /var/log/ipa-ansible-enroll.log
        state: absent
  when: enrolled is not failed  

- pause:
    prompt: "Waiting to ensure node is properly enrolled and replicated between IPA servers"
    seconds: 25
  when: enrolled is changed  

- name: Tuning sssd for large deployments
  blockinfile:
    path: /etc/sssd/sssd.conf
    insertafter: "krb5_store_password_if_offline = True"
    block: |
      ldap_deref_threshold = 0

  notify:
    - restart_sssd
  tags:
    - sssd

- name: Ensuring we have a local 2fa-kinit wrapper script for OTP
  template:
    src: 2fa-kinit.j2
    dest: /usr/local/bin/2fa-kinit
    mode: '0755'

- block:
    - name: Ensuring we have a place holder for TLS certs retrieved from IPA (if enabled)
      file:
        path: /etc/pki/centos
        state: directory
        owner: root
        group: admins
        mode: '0750'

    - name: Wrapper script to enroll/retrieve TLS/keytab for non enrolled nodes through delegation
      template:
        src: generate_ipa_tls_krb5.j2
        dest: /usr/libexec/centos/generate_ipa_tls_krb5
        mode: '0755'

  when: ipa_client_tls_delegated_host 
